### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by swincher4391** [Riebart/vivint.py#16]
RESTART: C:\Users\swincher4391\Documents\vivint.py-master\examples\switch.py =
Traceback (most recent call last):
  File "C:\Users\swincher4391\Documents\vivint.py-master\examples\switch.py", line 9, in <module>
    session = vivint.VivintCloudSession(<my username>,<my password>)
  File "C:\Users\swincher4391\Documents\vivint.py-master\examples\vivint.py", line 678, in __init__
    self.__auth_elements = self.__login(username, password) 
File "C:\Users\swincher4391\Documents\vivint.py-master\examples\vivint.py", line 897, in __login
    raise Exception("Unable to get Set-Cookie header from response")
Exception: Unable to get Set-Cookie header from response

**Comment by Riebart** [comment]
Yeah, I noticed that this is happening last week. I haven't used it in a while, so I suspect that they've rejiggered how their authentication flow works.

**Comment by swincher4391** [comment]
I am able to authenticate using pyvivint

from pyvivint.vivint import Vivint

vivint = Vivint(username=os.environ["username"], password=os.environ["password"])

and in his vivint.py

class Vivint:
    """Class for interacting with VivintSky API using asyncio"""

    def __init__(
        self,
        username: str,
        password: str,
        client_session: Optional[aiohttp.ClientSession] = None,
    ):
        self.__pubnub: pubnub.pubnub_asyncio.PubNubAsyncio = None
        self.vivintskyapi = VivintSkyApi(username, password, client_session)
        self.systems: List[pyvivint.system.System] = []

So I wasn't sure if there were multiple ways to authenticate or if this is now the only way to do it.

**Comment by Riebart** [comment]
So, this is bigger than just my auth flow (which, admittedly, _long_ predates the existence of any API, and so was built around reverse-engineering a webapp).

![image](https://user-images.githubusercontent.com/1278193/107465571-365f2100-6b28-11eb-9b8f-e8d5446b964f.png)

They're completely ripping out web-browser interaction. Which means they can gut and replace the entire server-side API at any point, and reverse-engineering it will depend entirely on reverse-engineering the mobile app (which uses TLS cert pinning, so MITM is a giant pain).

The reason that my library's auth no longer works is that they've totally changed how id token authentication (the flow I use) works. I can move everything to the server-side session-cookie-based one, but it's a bit of work.

One reason they might have wanted to do it is to enable realtime invalidation of the credentials, without needing to wait for JWTs to expire.

**Comment by Riebart** [comment]
Check out 798f7aaeac2a13d17e651c68c9bb8a7a6967b701 . I've converted the login API to the session cookie-based one, but didn't get a chance to debug anything robustly.

Yay, lack of test cases! 🗡️

**Comment by swincher4391** [comment]
Awesome. Do you know if there is any way I can write my own demo.py that sets a wireless sensor to bypass?what class/function would I use if this is possible?

![image](https://user-images.githubusercontent.com/14910253/107595574-aded8880-6bda-11eb-97a9-56bce6b52ed6.jpeg)

**Comment by Riebart** [comment]
I added support for them for you (26f9aae120c4302b7b2173cbde236cc38d270f1a).

```python
panels = session.get_panels()
panel = panels[0]
wireless_sensors = panels.get_devices(device_type_set=[
    vivint.VivintCloudSession.VivintDevice.DEVICE_TYPE_WIRELESS_SENSOR
])
wireless_sensors[0].bypass()
wireless_sensors[0].current_state()
wireless_sensors[0].enable()
```

For supported sensors, it'll report the battery level in percent. For those without a battery level (like a smoke detector that is hard-wired), it'll report `None`
