### ISSUE TITLE
Exception: Unable to find client id within the app.js package.

### ISSUE THREAD

**Issue by 7ooL** [Riebart/vivint.py#6]
File "vivint.py", line 675, in __login
    client_id = self.__get_client_id()
  File "vivint.py", line 659, in __get_client_id
    "Unable to find client id within the app.js package.")
Exception: Unable to find client id within the app.js package.

This error has been occurring for two days now. perhaps Vivint changed something?

**Comment by 7ooL** [comment]
fixed with the following change:
FROM:
```python
match = re.search(r'r="id_token",o="([0-9a-f]*)"', resp.data.decode())
```
TO:
```python
match = re.search(r'r="id_token",a="([0-9a-f]*)"', resp.data.decode())
```

**Comment by Riebart** [comment]
This is fixed both in the change in the regex, and then by switching entirely to using a separate API endpoint.
